<?php
$lang['home_maintext'] = "A következő generációs operációs rendszer. Könnyű és szép. Teljesen új alkalmazásokkal, kifinomult megjelenéssel. Nevezzünk meg egy árat támogatás céljából, vagy töltsük le ingyenesen.";
$lang['home_download'] = "Letöltés";
$lang['home_payment'] = "Támogatás";
$lang['home_amount'] = "Összeg"; // Amount of money
$lang['home_method'] = "Metódus"; // Method of payment
$lang['home_processor'] = "Processzor";
$lang['home_creditcard'] = "Hitelkártya";
$lang['home_direct'] = "Közvetlen"; // Direct download (via HTTP)
$lang['home_luna_free'] = "Ingyenes letöltés";
$lang['home_elementary_is'] = "elementary is:";
$lang['home_point1'] = "Közösségi indíttatás.";
$lang['home_expl1'] = "Az elementary os egyetlen célja: a lehető legjobb felhasználói élmény és közösség létrehozása. Hajt minket a vágy, hogy a legjobb operációs rendszert készítsük el. A közreműködők nem profit-maximalizálók, ők az elöbb említett célra maximalizálók.";
$lang['home_point2'] = "Átlátható és nyitott.";
$lang['home_expl2'] = "Hiszünk abban, hogy a hatalom a nyílt forráskódú és a globális együttműködésben rejlik. Ez azt jelenti, hogy bárki szabadon letöltheti, használhatja, módosíthatja, és hozzájárulhat a forráshoz ötleteivel, fejlesztéseivel. A kód kidolgozását szabadon el lehet végezni és beküldés után felülvizsgálatra kerül sor, majd a világ minden tájáról több tízezer fejlesztő ellenőrzi a kódot ls csaj ezután kerül bele a rendszerbe.";
$lang['home_point3'] = "Szép és használható.";
$lang['home_expl3'] = "Az elementary operációs rendszert ügyes tervezők és fejlesztők készítik, akik úgy vélik, hogy a számítógép is lehet könnyű, szórakoztató, és gyönyörű. A tervezés első fázisától biztosítjuk a minőséget és használhatóságot.";
$lang['home_point4'] = "Modern számítástechnika.";
$lang['home_expl4'] = "Az elementary os egy ingyenes alternatívája a Windows és Mac os x operációs rendszereknek. Magába foglalja mindazokat amit egy modern rendszertől elvárhatunk. Egy gyors böngészőt, alkalmazásközpontot, több ezer alkalmazást, ingyenes frissítéseket és vírusmentességet.";
$lang['home_point5'] = "Sebesség";
$lang['home_expl5'] = "Az elementary operációs rendszert már az alapoktól kezdve úgy terveztük, hogy könnyű és gyors legyen. Telepítés után pillanatok alatt feláll a rendszer és már használhatjuk is minimális erőforrások igénybevételével. A rendszerünk a Linux Foundation alapjaira építkezik amit a világ leggyorsabb szuperszámítógépein is használnak és a leggyorsabb operációs rendszernek választották a világon.";
$lang['home_point6'] = "Lényeges alkalmazások";
$lang['home_expl6'] = "Amikor az elementary os került telepítésre, akkor nem csak egy operációs rendszert telepítünk hanem rengeteg kiváló csomagot és személyreszabott alkalmazásokat, amelyek segítségével rögtön használatba vehetjük a rendszerünket. Azonnal és egyszerűen böngészhetünk az interneten, ellenőrizhetjük e-mailjeinket, zenét hallgatnunk, és kezelhetjük nagy örömmel a mindennapi feladatainkat.";
$lang['home_app1'] = "Böngésszünk az albumokban, rendezzük a listákat, értékeljük zenéket, és tekintsük meg a hasonló szerzeményeket.";
$lang['home_app2'] = "A Midori egy C-ben írt, GTK+ alapú webböngésző, amely a WebKit leképező motort használja, csakúgy mint az Apple Safari vagy a Google Chrome.";
$lang['home_app3'] = "Érjük el barátainkat, ismerőseinket a Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! segítségével.";
$lang['home_app4'] = "Érjük el leveleinket közvetlenül az asztalon. Akár több fiókot is felvehetünk.";
$lang['home_app5'] = "Importáljuk, rendszerezzük, szerkeszzük képeinket, hozzunk létre diavetítéseket majd osszuk meg a Facebookon vagy Flickeren.";
$lang['home_app6'] = "Mindig az élvonalban maradunk a legújabb frissítésekkel örökre ingyen.";
$lang['home_point7'] = "Teljes hozzáférés";
$lang['home_expl7'] = "Különböző emberek a világ minden tájáról építik az elementary operációs rendszert. Így nem meglepő, hogy szemelőtt tartjuk a hallás, látás és mozgáskorlátozott embereket is.";
$lang['home_point8'] = "Biztonság és megbízhatóság";
$lang['home_expl8'] = "Az elementary os alapja a Linux sziklaszilárd kernel (Ugyanaz a szoftver amelyet az Amerikai Védelmi Minisztérium, a Kínai Bank és sok más szerv is használ nagy megelégetettséggel.) amely nem az ismert vírusok körében. Ez azt jelenti, hogy nem kell telepíteni bosszantó anti-vírus szoftvert ami lelassítja a rendszert. Az elementary os sűrűn kap biztonsági frissítéseket, így mindig naprakész és biztonságos a rendszer.";
$lang['home_point9'] = "100% Ingyenes";
$lang['home_expl9'] = "Az elementary os egy teljesen ingyenes nyílt forráskódú operációs rendszer. Nincsenek rejtett költséges díjak, zavaros felhasználói szerződések, próbaidő, vagy korlátozó másolásvédelem. Telepíthetjük a rendszert annyi számítógépre amennyire csak szeretnénk, lemásolhatjuk, tovább fejlethetjük és akár barátainknak is oda adhatjuk.";
$lang['home_point10'] = "Kész alkalmazások";
$lang['home_expl10'] = "Az elementary os egy beépített alkalmazásközpontot tartalmaz, amely tele van több ezer ingyenes ellenőrzött alkalmazásokkal. Gyorsan megtaláljuk azt az alkalmazást amit keresünk és nem kell aggódnunk malware vírusok miatt az interneten.";
$lang['home_whatis'] = "Mi az"; // Whole sentence reads "what is elementary OS?"
